/*
 * Copyright (C) 2025 Microchip Technology Inc.  All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef M2D_VIVANTE_GC_PRIV_H
#define M2D_VIVANTE_GC_PRIV_H

#ifndef VIVS_DE_ALPHA_MODES_GLOBAL_SRC_ALPHA_MODE
#define VIVS_DE_ALPHA_MODES_GLOBAL_SRC_ALPHA_MODE(x) (((x) << VIVS_DE_ALPHA_MODES_GLOBAL_SRC_ALPHA_MODE__SHIFT) & VIVS_DE_ALPHA_MODES_GLOBAL_SRC_ALPHA_MODE__MASK)
#endif

#ifndef VIVS_DE_ALPHA_MODES_GLOBAL_DST_ALPHA_MODE
#define VIVS_DE_ALPHA_MODES_GLOBAL_DST_ALPHA_MODE(x) (((x) << VIVS_DE_ALPHA_MODES_GLOBAL_DST_ALPHA_MODE__SHIFT) & VIVS_DE_ALPHA_MODES_GLOBAL_DST_ALPHA_MODE__MASK)
#endif

#ifndef VIVS_DE_ALPHA_MODES_PE10_SRC_COLOR_MULTIPLY
#define VIVS_DE_ALPHA_MODES_PE10_SRC_COLOR_MULTIPLY(x) (((x) << VIVS_DE_ALPHA_MODES_PE10_SRC_COLOR_MULTIPLY__SHIFT) & VIVS_DE_ALPHA_MODES_PE10_SRC_COLOR_MULTIPLY__MASK)
#endif

#ifndef VIVS_DE_ALPHA_MODES_PE10_DST_COLOR_MULTIPLY
#define VIVS_DE_ALPHA_MODES_PE10_DST_COLOR_MULTIPLY(x) (((x) << VIVS_DE_ALPHA_MODES_PE10_DST_COLOR_MULTIPLY__SHIFT) & VIVS_DE_ALPHA_MODES_PE10_DST_COLOR_MULTIPLY__MASK)
#endif

#ifndef VIVS_DE_ALPHA_MODES_SRC_ALPHA_FACTOR
#define VIVS_DE_ALPHA_MODES_SRC_ALPHA_FACTOR(x) (((x) << VIVS_DE_ALPHA_MODES_SRC_ALPHA_FACTOR__SHIFT) & VIVS_DE_ALPHA_MODES_SRC_ALPHA_FACTOR__MASK)
#endif

#ifndef VIVS_DE_ALPHA_MODES_DST_ALPHA_FACTOR
#define VIVS_DE_ALPHA_MODES_DST_ALPHA_FACTOR(x) (((x) << VIVS_DE_ALPHA_MODES_DST_ALPHA_FACTOR__SHIFT) & VIVS_DE_ALPHA_MODES_DST_ALPHA_FACTOR__MASK)
#endif

#ifndef VIVS_DE_COLOR_MULTIPLY_MODES_SRC_PREMULTIPLY
#define VIVS_DE_COLOR_MULTIPLY_MODES_SRC_PREMULTIPLY(x) (((x) << VIVS_DE_COLOR_MULTIPLY_MODES_SRC_PREMULTIPLY__SHIFT) & VIVS_DE_COLOR_MULTIPLY_MODES_SRC_PREMULTIPLY__MASK)
#endif

#ifndef VIVS_DE_COLOR_MULTIPLY_MODES_DST_PREMULTIPLY
#define VIVS_DE_COLOR_MULTIPLY_MODES_DST_PREMULTIPLY(x) (((x) << VIVS_DE_COLOR_MULTIPLY_MODES_DST_PREMULTIPLY__SHIFT) & VIVS_DE_COLOR_MULTIPLY_MODES_DST_PREMULTIPLY__MASK)
#endif

#ifndef VIVS_DE_COLOR_MULTIPLY_MODES_SRC_GLOBAL_PREMULTIPLY
#define VIVS_DE_COLOR_MULTIPLY_MODES_SRC_GLOBAL_PREMULTIPLY(x) (((x) << VIVS_DE_COLOR_MULTIPLY_MODES_SRC_GLOBAL_PREMULTIPLY__SHIFT) & VIVS_DE_COLOR_MULTIPLY_MODES_SRC_GLOBAL_PREMULTIPLY__MASK)
#endif

#define VIVS_DE_BLOCK8_PE_TRANSPARENCY(i0)			VIVS_DE_BLOCK8_TRANSPARENCY(i0)
#define VIVS_DE_BLOCK8_PE_CONTROL(i0)				VIVS_DE_BLOCK8_CONTROL(i0)

#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT(i0)		       (0x00012d00 + 0x4*(i0))
#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT__ESIZE			0x00000004
#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT__LEN			0x00000008
#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT_X__MASK			0x00007fff
#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT_X__SHIFT			0
#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT_X(x)			(((x) << VIVS_DE_BLOCK8_CLIP_TOP_LEFT_X__SHIFT) & VIVS_DE_BLOCK8_CLIP_TOP_LEFT_X__MASK)
#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT_Y__MASK			0x7fff0000
#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT_Y__SHIFT			16
#define VIVS_DE_BLOCK8_CLIP_TOP_LEFT_Y(y)			(((y) << VIVS_DE_BLOCK8_CLIP_TOP_LEFT_Y__SHIFT) & VIVS_DE_BLOCK8_CLIP_TOP_LEFT_Y__MASK)

#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT(i0)		       (0x00012d20 + 0x4*(i0))
#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT__ESIZE			0x00000004
#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT__LEN			0x00000008
#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_X__MASK		0x00007fff
#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_X__SHIFT		0
#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_X(x)			(((x) << VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_X__SHIFT) & VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_X__MASK)
#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_Y__MASK		0x7fff0000
#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_Y__SHIFT		16
#define VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_Y(y)			(((y) << VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_Y__SHIFT) & VIVS_DE_BLOCK8_CLIP_BOTTOM_RIGHT_Y__MASK)

#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT(i0)		       (0x00012d40 + 0x4*(i0))
#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT__ESIZE		0x00000004
#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT__LEN			0x00000008
#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_X__MASK		0x00007fff
#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_X__SHIFT		0
#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_X(x)			(((x) << VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_X__SHIFT) & VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_X__MASK)
#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_Y__MASK		0x7fff0000
#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_Y__SHIFT		16
#define VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_Y(y)			(((y) << VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_Y__SHIFT) & VIVS_DE_BLOCK8_DEST_RECT_TOP_LEFT_Y__MASK)

#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT(i0)	       (0x00012d60 + 0x4*(i0))
#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT__ESIZE		0x00000004
#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT__LEN		0x00000008
#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_X__MASK		0x00007fff
#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_X__SHIFT		0
#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_X(x)		(((x) << VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_X__SHIFT) & VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_X__MASK)
#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_Y__MASK		0x7fff0000
#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_Y__SHIFT		16
#define VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_Y(y)		(((y) << VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_Y__SHIFT) & VIVS_DE_BLOCK8_DEST_RECT_BOTTOM_RIGHT_Y__MASK)

#define VIVS_DE_BLOCK8_STRETCH_FACTOR_LOW(i0)		       (0x00012d80 + 0x4*(i0))
#define VIVS_DE_BLOCK8_STRETCH_FACTOR_LOW_X__MASK		0x7fffffff
#define VIVS_DE_BLOCK8_STRETCH_FACTOR_LOW_X__SHIFT		0
#define VIVS_DE_BLOCK8_STRETCH_FACTOR_LOW_X(x)			(((x) << VIVS_DE_BLOCK8_STRETCH_FACTOR_LOW_X__SHIFT) & VIVS_DE_BLOCK8_STRETCH_FACTOR_LOW_X__MASK)

#define VIVS_DE_BLOCK8_STRETCH_FACTOR_HIGH(i0)		       (0x00012da0 +0x4*(i0))
#define VIVS_DE_BLOCK8_STRETCH_FACTOR_HIGH_Y__MASK		0x7fffffff
#define VIVS_DE_BLOCK8_STRETCH_FACTOR_HIGH_Y__SHIFT		0
#define VIVS_DE_BLOCK8_STRETCH_FACTOR_HIGH_Y(x)			(((x) << VIVS_DE_BLOCK8_STRETCH_FACTOR_HIGH_Y__SHIFT) & VIVS_DE_BLOCK8_STRETCH_FACTOR_HIGH_Y__MASK)

#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG(i0)		       (0x00012e80 + 0x4*(i0))
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_SRC_CMD__MASK		0x00000007
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_SRC_CMD__SHIFT		0
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_SRC_CMD_BIT_BLT		0x00000000
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_SRC_CMD_STRETCH_BLT	0x00000001
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_SRC_CMD__MASK	0x00000008
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_SRC_CMD__SHIFT	3
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_SRC_CMD_ENABLED	0x00000000
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_SRC_CMD_MASKED	0x00000008
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_GDI_STRE__MASK		0x00000010
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_GDI_STRE__SHIFT		4
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_GDI_STRE_DISABLED	0x00000000
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_GDI_STRE_ENABLED	0x00000010
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_GDI_STRE__MASK	0x00000020
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_GDI_STRE__SHIFT	5
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_GDI_STRE_DISABLED	0x00000000
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_GDI_STRE_ENABLED	0x00000020
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_INITIAL_ERROR__MASK	0x00000040
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_INITIAL_ERROR__SHIFT	6
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_INITIAL_ERROR_DISABLED	0x00000000
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_INITIAL_ERROR_ENABLED	0x00000040
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_INITIAL_ERROR__MASK	0x00000080
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_INITIAL_ERROR__SHIFT	7
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_INITIAL_ERROR_DISABLED	0x00000000
#define VIVS_DE_BLOCK8_MULTI_SRC_CONFIG_MASK_INITIAL_ERROR_ENABLED	0x00000080

#define VIVS_DE_BLOCK8_SRC_ORIGIN_FRACTION(i0)		       (0x00012f80 + 0x4*(i0))
#define VIVS_DE_BLOCK8_SRC_ORIGIN_FRACTION_X__MASK		0x0000ffff
#define VIVS_DE_BLOCK8_SRC_ORIGIN_FRACTION_X__SHIFT		0
#define VIVS_DE_BLOCK8_SRC_ORIGIN_FRACTION_X(x)			(((x) << VIVS_DE_BLOCK8_MULTI_SRC_ORIGIN_FACTION_X__SHIFT) & VIVS_DE_BLOCK8_MULTI_SRC_ORIGIN_FACTION_X__MASK)
#define VIVS_DE_BLOCK8_SRC_ORIGIN_FRACTION_Y__MASK		0xffff0000
#define VIVS_DE_BLOCK8_SRC_ORIGIN_FRACTION_Y__SHIFT		16
#define VIVS_DE_BLOCK8_SRC_ORIGIN_FRACTION_Y(y)			(((y) << VIVS_DE_BLOCK8_MULTI_SRC_ORIGIN_FACTION_Y__SHIFT) & VIVS_DE_BLOCK8_MULTI_SRC_ORIGIN_FACTION_Y__MASK)

#define VIVS_DE_DEST_CONFIG_STRETCH_QUAD__MASK			0x08000000
#define VIVS_DE_DEST_CONFIG_STRETCH_QUAD__SHIFT			27
#define VIVS_DE_DEST_CONFIG_STRETCH_QUAD_ENABLED		0x00000000
#define VIVS_DE_DEST_CONFIG_STRETCH_QUAD_DISABLED		0x08000000

#endif /* M2D_VIVANTE_GC_PRIV_H */
